### ISSUE TITLE
Ocultar Tipo de Pessoa e Inscrição Estadual

### ISSUE THREAD

**Issue by casaud** [deivisonarthur/OSC-Magento-Brasil-6-Pro#272]
Olá!
Alguém sabe ocultar os campos de Pessoa Física / Jurídica e Inscrição estadual no OSC?

**Comment by hansbonini** [comment]
Abre o arquivo: ```/skin/frontend/base/default/onestepcheckout/css/onestepcheckout.css``` e adicione o seguinte código na última linha:

```css
li.control.tipopessoa {
 display: none;
}
```

**Comment by casaud** [comment]
Olá,

Não funcionou...

Em 30 de setembro de 2016 07:02, Hans Bonini <notifications@github.com>
escreveu:

**Comment by casaud** [comment]
Ah... consegui! Coloquei assim:
.form-list li.control.tipopessoa {display: none;}

Agora falta tirar a frase "Campos obrigatório"

**Comment by hansbonini** [comment]
IE você remove por dentro do painel mesmo. Quanto ao Campos Obrigatórios*, não acho certo remover, mas caso queira:
```css

ul li p.required {
 display: none !important;
}

```
